Fix regression causing FTBFS in some circumstances.
  - Fix for GitHub issue #1: Undefined reference to `ssh_config_parse_line'.
    The implementation of ssh_config_parse_line was removed with commit
    fa1a4e.  This is reinstated since it is used by some of the examples.
  - Bump version to 1.1.3.