Update libssh port to 0.10 and stability improvements.
  - Update the port to use commit e8322817a9e5aaef0698d779ddd467a209a85d85
    from libssh, i.e. 0.10.4 stable.
  - Update all examples to match port.
  - Use libssh built-in poll code instead of esp32 supplied poll code.
    This fixes disconnects on incoming ssh sessions (especially on a
    fast media such as Ethernet).
  - Fix Arduino FTBFS following PlatformIO patch in commit 4f3da877:
      inet.h:71:29: error: 'IPADDR_NONE' was not declared in this scope
  - Bump version to 3.0.0.
  - Initial ESP32-S3 board support.